<?php


use Phinx\Seed\AbstractSeed;

class KinhMachDetail extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run()
    {
        $data = [
            [
                "kinh_mach_id" => 1,
                "level" => 1,
                "chinh_xac" => 6,
                "ne_tranh" => 6,
                "noi_phong" => 3,
                "bo_qua_noi_phong" => 8,
                "khi_huyet" => 78,
                "noi_luc" => 19,
                "chan_khi_tien_cap" => 10528,
                "chan_khi_tong" => 0,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 2,
                "chinh_xac" => 6,
                "ne_tranh" => 6,
                "noi_phong" => 3,
                "bo_qua_noi_phong" => 8,
                "khi_huyet" => 84,
                "noi_luc" => 20,
                "chan_khi_tien_cap" => 12712,
                "chan_khi_tong" => 10528,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 3,
                "chinh_xac" => 7,
                "ne_tranh" => 7,
                "noi_phong" => 3,
                "bo_qua_noi_phong" => 9,
                "khi_huyet" => 90,
                "noi_luc" => 22,
                "chan_khi_tien_cap" => 14952,
                "chan_khi_tong" => 23240,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 4,
                "chinh_xac" => 7,
                "ne_tranh" => 7,
                "noi_phong" => 3,
                "bo_qua_noi_phong" => 9,
                "khi_huyet" => 96,
                "noi_luc" => 23,
                "chan_khi_tien_cap" => 17248,
                "chan_khi_tong" => 38192,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 5,
                "chinh_xac" => 8,
                "ne_tranh" => 8,
                "noi_phong" => 3,
                "bo_qua_noi_phong" => 10,
                "khi_huyet" => 102,
                "noi_luc" => 24,
                "chan_khi_tien_cap" => 19600,
                "chan_khi_tong" => 55440,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 6,
                "chinh_xac" => 8,
                "ne_tranh" => 8,
                "noi_phong" => 3,
                "bo_qua_noi_phong" => 10,
                "khi_huyet" => 108,
                "noi_luc" => 26,
                "chan_khi_tien_cap" => 22008,
                "chan_khi_tong" => 75040,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 7,
                "chinh_xac" => 9,
                "ne_tranh" => 9,
                "noi_phong" => 4,
                "bo_qua_noi_phong" => 12,
                "khi_huyet" => 114,
                "noi_luc" => 27,
                "chan_khi_tien_cap" => 25872,
                "chan_khi_tong" => 97048,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 8,
                "chinh_xac" => 9,
                "ne_tranh" => 9,
                "noi_phong" => 4,
                "bo_qua_noi_phong" => 12,
                "khi_huyet" => 120,
                "noi_luc" => 29,
                "chan_khi_tien_cap" => 29792,
                "chan_khi_tong" => 122920,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 9,
                "chinh_xac" => 10,
                "ne_tranh" => 10,
                "noi_phong" => 4,
                "bo_qua_noi_phong" => 13,
                "khi_huyet" => 126,
                "noi_luc" => 30,
                "chan_khi_tien_cap" => 37268,
                "chan_khi_tong" => 152712,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 10,
                "chinh_xac" => 10,
                "ne_tranh" => 10,
                "noi_phong" => 4,
                "bo_qua_noi_phong" => 13,
                "khi_huyet" => 132,
                "noi_luc" => 31,
                "chan_khi_tien_cap" => 102500,
                "chan_khi_tong" => 189980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 11,
                "chinh_xac" => 11,
                "ne_tranh" => 11,
                "noi_phong" => 5,
                "bo_qua_noi_phong" => 14,
                "khi_huyet" => 138,
                "noi_luc" => 33,
                "chan_khi_tien_cap" => 103025,
                "chan_khi_tong" => 292480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 12,
                "chinh_xac" => 11,
                "ne_tranh" => 11,
                "noi_phong" => 5,
                "bo_qua_noi_phong" => 14,
                "khi_huyet" => 144,
                "noi_luc" => 34,
                "chan_khi_tien_cap" => 103600,
                "chan_khi_tong" => 395505,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 13,
                "chinh_xac" => 12,
                "ne_tranh" => 12,
                "noi_phong" => 5,
                "bo_qua_noi_phong" => 15,
                "khi_huyet" => 150,
                "noi_luc" => 36,
                "chan_khi_tien_cap" => 104225,
                "chan_khi_tong" => 499105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 14,
                "chinh_xac" => 12,
                "ne_tranh" => 12,
                "noi_phong" => 5,
                "bo_qua_noi_phong" => 15,
                "khi_huyet" => 156,
                "noi_luc" => 37,
                "chan_khi_tien_cap" => 104900,
                "chan_khi_tong" => 603330,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 15,
                "chinh_xac" => 13,
                "ne_tranh" => 13,
                "noi_phong" => 5,
                "bo_qua_noi_phong" => 16,
                "khi_huyet" => 162,
                "noi_luc" => 38,
                "chan_khi_tien_cap" => 105625,
                "chan_khi_tong" => 708230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 16,
                "chinh_xac" => 13,
                "ne_tranh" => 13,
                "noi_phong" => 5,
                "bo_qua_noi_phong" => 16,
                "khi_huyet" => 168,
                "noi_luc" => 40,
                "chan_khi_tien_cap" => 106400,
                "chan_khi_tong" => 813855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 17,
                "chinh_xac" => 14,
                "ne_tranh" => 14,
                "noi_phong" => 6,
                "bo_qua_noi_phong" => 18,
                "khi_huyet" => 174,
                "noi_luc" => 41,
                "chan_khi_tien_cap" => 107225,
                "chan_khi_tong" => 920255,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 18,
                "chinh_xac" => 14,
                "ne_tranh" => 14,
                "noi_phong" => 6,
                "bo_qua_noi_phong" => 18,
                "khi_huyet" => 179,
                "noi_luc" => 43,
                "chan_khi_tien_cap" => 108100,
                "chan_khi_tong" => 1027480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 19,
                "chinh_xac" => 15,
                "ne_tranh" => 15,
                "noi_phong" => 6,
                "bo_qua_noi_phong" => 19,
                "khi_huyet" => 185,
                "noi_luc" => 44,
                "chan_khi_tien_cap" => 109025,
                "chan_khi_tong" => 1135580,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 20,
                "chinh_xac" => 15,
                "ne_tranh" => 15,
                "noi_phong" => 6,
                "bo_qua_noi_phong" => 19,
                "khi_huyet" => 191,
                "noi_luc" => 46,
                "chan_khi_tien_cap" => 110000,
                "chan_khi_tong" => 1244605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 21,
                "chinh_xac" => 16,
                "ne_tranh" => 16,
                "noi_phong" => 7,
                "bo_qua_noi_phong" => 20,
                "khi_huyet" => 197,
                "noi_luc" => 47,
                "chan_khi_tien_cap" => 111025,
                "chan_khi_tong" => 1354605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 22,
                "chinh_xac" => 16,
                "ne_tranh" => 16,
                "noi_phong" => 7,
                "bo_qua_noi_phong" => 20,
                "khi_huyet" => 203,
                "noi_luc" => 48,
                "chan_khi_tien_cap" => 112100,
                "chan_khi_tong" => 1465630,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 23,
                "chinh_xac" => 17,
                "ne_tranh" => 17,
                "noi_phong" => 7,
                "bo_qua_noi_phong" => 21,
                "khi_huyet" => 209,
                "noi_luc" => 50,
                "chan_khi_tien_cap" => 113225,
                "chan_khi_tong" => 1577730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 24,
                "chinh_xac" => 17,
                "ne_tranh" => 17,
                "noi_phong" => 7,
                "bo_qua_noi_phong" => 21,
                "khi_huyet" => 215,
                "noi_luc" => 51,
                "chan_khi_tien_cap" => 114400,
                "chan_khi_tong" => 1690955,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 25,
                "chinh_xac" => 18,
                "ne_tranh" => 18,
                "noi_phong" => 7,
                "bo_qua_noi_phong" => 22,
                "khi_huyet" => 221,
                "noi_luc" => 53,
                "chan_khi_tien_cap" => 115625,
                "chan_khi_tong" => 1805355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 26,
                "chinh_xac" => 18,
                "ne_tranh" => 18,
                "noi_phong" => 7,
                "bo_qua_noi_phong" => 22,
                "khi_huyet" => 227,
                "noi_luc" => 54,
                "chan_khi_tien_cap" => 116900,
                "chan_khi_tong" => 1920980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 27,
                "chinh_xac" => 19,
                "ne_tranh" => 19,
                "noi_phong" => 8,
                "bo_qua_noi_phong" => 24,
                "khi_huyet" => 233,
                "noi_luc" => 55,
                "chan_khi_tien_cap" => 118225,
                "chan_khi_tong" => 2037880,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 28,
                "chinh_xac" => 19,
                "ne_tranh" => 19,
                "noi_phong" => 8,
                "bo_qua_noi_phong" => 24,
                "khi_huyet" => 239,
                "noi_luc" => 57,
                "chan_khi_tien_cap" => 119600,
                "chan_khi_tong" => 2156105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 29,
                "chinh_xac" => 20,
                "ne_tranh" => 20,
                "noi_phong" => 8,
                "bo_qua_noi_phong" => 25,
                "khi_huyet" => 245,
                "noi_luc" => 58,
                "chan_khi_tien_cap" => 121025,
                "chan_khi_tong" => 2275705,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 30,
                "chinh_xac" => 20,
                "ne_tranh" => 20,
                "noi_phong" => 8,
                "bo_qua_noi_phong" => 25,
                "khi_huyet" => 251,
                "noi_luc" => 60,
                "chan_khi_tien_cap" => 122500,
                "chan_khi_tong" => 2396730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 31,
                "chinh_xac" => 21,
                "ne_tranh" => 21,
                "noi_phong" => 9,
                "bo_qua_noi_phong" => 26,
                "khi_huyet" => 257,
                "noi_luc" => 61,
                "chan_khi_tien_cap" => 124025,
                "chan_khi_tong" => 2519230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 32,
                "chinh_xac" => 21,
                "ne_tranh" => 21,
                "noi_phong" => 9,
                "bo_qua_noi_phong" => 26,
                "khi_huyet" => 263,
                "noi_luc" => 63,
                "chan_khi_tien_cap" => 125600,
                "chan_khi_tong" => 2643255,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 33,
                "chinh_xac" => 22,
                "ne_tranh" => 22,
                "noi_phong" => 9,
                "bo_qua_noi_phong" => 27,
                "khi_huyet" => 269,
                "noi_luc" => 64,
                "chan_khi_tien_cap" => 127225,
                "chan_khi_tong" => 2768855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 34,
                "chinh_xac" => 22,
                "ne_tranh" => 22,
                "noi_phong" => 9,
                "bo_qua_noi_phong" => 27,
                "khi_huyet" => 274,
                "noi_luc" => 65,
                "chan_khi_tien_cap" => 128900,
                "chan_khi_tong" => 2896080,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 35,
                "chinh_xac" => 23,
                "ne_tranh" => 23,
                "noi_phong" => 9,
                "bo_qua_noi_phong" => 28,
                "khi_huyet" => 280,
                "noi_luc" => 67,
                "chan_khi_tien_cap" => 130625,
                "chan_khi_tong" => 3024980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 36,
                "chinh_xac" => 23,
                "ne_tranh" => 23,
                "noi_phong" => 9,
                "bo_qua_noi_phong" => 28,
                "khi_huyet" => 286,
                "noi_luc" => 68,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 132400,
                "chan_khi_tong" => 3155605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 37,
                "chinh_xac" => 24,
                "ne_tranh" => 24,
                "noi_phong" => 10,
                "bo_qua_noi_phong" => 30,
                "khi_huyet" => 292,
                "noi_luc" => 70,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 134225,
                "chan_khi_tong" => 3288005,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 38,
                "chinh_xac" => 24,
                "ne_tranh" => 24,
                "noi_phong" => 10,
                "bo_qua_noi_phong" => 30,
                "khi_huyet" => 298,
                "noi_luc" => 71,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 136100,
                "chan_khi_tong" => 3422230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 39,
                "chinh_xac" => 25,
                "ne_tranh" => 25,
                "noi_phong" => 10,
                "bo_qua_noi_phong" => 31,
                "khi_huyet" => 304,
                "noi_luc" => 72,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 138025,
                "chan_khi_tong" => 3558330,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 40,
                "chinh_xac" => 25,
                "ne_tranh" => 25,
                "noi_phong" => 10,
                "bo_qua_noi_phong" => 31,
                "khi_huyet" => 310,
                "noi_luc" => 74,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 140000,
                "chan_khi_tong" => 3696355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 41,
                "chinh_xac" => 26,
                "ne_tranh" => 26,
                "noi_phong" => 11,
                "bo_qua_noi_phong" => 32,
                "khi_huyet" => 316,
                "noi_luc" => 75,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 142025,
                "chan_khi_tong" => 3836355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 42,
                "chinh_xac" => 26,
                "ne_tranh" => 26,
                "noi_phong" => 11,
                "bo_qua_noi_phong" => 32,
                "khi_huyet" => 322,
                "noi_luc" => 77,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 144100,
                "chan_khi_tong" => 3978380,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 43,
                "chinh_xac" => 27,
                "ne_tranh" => 27,
                "noi_phong" => 11,
                "bo_qua_noi_phong" => 33,
                "khi_huyet" => 328,
                "noi_luc" => 78,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 146225,
                "chan_khi_tong" => 4122480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 44,
                "chinh_xac" => 27,
                "ne_tranh" => 27,
                "noi_phong" => 11,
                "bo_qua_noi_phong" => 33,
                "khi_huyet" => 334,
                "noi_luc" => 79,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 148400,
                "chan_khi_tong" => 4268705,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 45,
                "chinh_xac" => 27,
                "ne_tranh" => 27,
                "noi_phong" => 11,
                "bo_qua_noi_phong" => 34,
                "khi_huyet" => 340,
                "noi_luc" => 81,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 150625,
                "chan_khi_tong" => 4417105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 46,
                "chinh_xac" => 27,
                "ne_tranh" => 27,
                "noi_phong" => 11,
                "bo_qua_noi_phong" => 34,
                "khi_huyet" => 346,
                "noi_luc" => 82,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 152900,
                "chan_khi_tong" => 4567730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 47,
                "chinh_xac" => 28,
                "ne_tranh" => 28,
                "noi_phong" => 12,
                "bo_qua_noi_phong" => 36,
                "khi_huyet" => 352,
                "noi_luc" => 84,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 155225,
                "chan_khi_tong" => 4720630,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 48,
                "chinh_xac" => 28,
                "ne_tranh" => 28,
                "noi_phong" => 12,
                "bo_qua_noi_phong" => 36,
                "khi_huyet" => 358,
                "noi_luc" => 85,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 157600,
                "chan_khi_tong" => 4875855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 49,
                "chinh_xac" => 29,
                "ne_tranh" => 29,
                "noi_phong" => 12,
                "bo_qua_noi_phong" => 37,
                "khi_huyet" => 364,
                "noi_luc" => 87,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 160025,
                "chan_khi_tong" => 5033455,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 50,
                "chinh_xac" => 29,
                "ne_tranh" => 29,
                "noi_phong" => 12,
                "bo_qua_noi_phong" => 37,
                "khi_huyet" => 370,
                "noi_luc" => 88,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 162500,
                "chan_khi_tong" => 5193480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 51,
                "chinh_xac" => 30,
                "ne_tranh" => 30,
                "noi_phong" => 13,
                "bo_qua_noi_phong" => 38,
                "khi_huyet" => 375,
                "noi_luc" => 89,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 165025,
                "chan_khi_tong" => 5355980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 52,
                "chinh_xac" => 30,
                "ne_tranh" => 30,
                "noi_phong" => 13,
                "bo_qua_noi_phong" => 38,
                "khi_huyet" => 381,
                "noi_luc" => 91,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 167600,
                "chan_khi_tong" => 5521005,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 53,
                "chinh_xac" => 31,
                "ne_tranh" => 31,
                "noi_phong" => 13,
                "bo_qua_noi_phong" => 39,
                "khi_huyet" => 387,
                "noi_luc" => 92,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 170225,
                "chan_khi_tong" => 5688605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 54,
                "chinh_xac" => 31,
                "ne_tranh" => 31,
                "noi_phong" => 13,
                "bo_qua_noi_phong" => 39,
                "khi_huyet" => 393,
                "noi_luc" => 94,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 172900,
                "chan_khi_tong" => 5858830,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 55,
                "chinh_xac" => 32,
                "ne_tranh" => 32,
                "noi_phong" => 13,
                "bo_qua_noi_phong" => 40,
                "khi_huyet" => 399,
                "noi_luc" => 95,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 175625,
                "chan_khi_tong" => 6031730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 56,
                "chinh_xac" => 32,
                "ne_tranh" => 32,
                "noi_phong" => 13,
                "bo_qua_noi_phong" => 40,
                "khi_huyet" => 405,
                "noi_luc" => 96,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 178400,
                "chan_khi_tong" => 6207355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 57,
                "chinh_xac" => 33,
                "ne_tranh" => 33,
                "noi_phong" => 14,
                "bo_qua_noi_phong" => 42,
                "khi_huyet" => 411,
                "noi_luc" => 98,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 181225,
                "chan_khi_tong" => 6385755,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 58,
                "chinh_xac" => 33,
                "ne_tranh" => 33,
                "noi_phong" => 14,
                "bo_qua_noi_phong" => 42,
                "khi_huyet" => 417,
                "noi_luc" => 99,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 184100,
                "chan_khi_tong" => 6566980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 59,
                "chinh_xac" => 34,
                "ne_tranh" => 34,
                "noi_phong" => 14,
                "bo_qua_noi_phong" => 43,
                "khi_huyet" => 423,
                "noi_luc" => 101,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 187025,
                "chan_khi_tong" => 6751080,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 60,
                "chinh_xac" => 34,
                "ne_tranh" => 34,
                "noi_phong" => 14,
                "bo_qua_noi_phong" => 43,
                "khi_huyet" => 429,
                "noi_luc" => 102,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 190000,
                "chan_khi_tong" => 6938105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 61,
                "chinh_xac" => 35,
                "ne_tranh" => 35,
                "noi_phong" => 15,
                "bo_qua_noi_phong" => 44,
                "khi_huyet" => 435,
                "noi_luc" => 104,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 193025,
                "chan_khi_tong" => 7128105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 62,
                "chinh_xac" => 35,
                "ne_tranh" => 35,
                "noi_phong" => 15,
                "bo_qua_noi_phong" => 44,
                "khi_huyet" => 441,
                "noi_luc" => 105,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 196100,
                "chan_khi_tong" => 7321130,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 63,
                "chinh_xac" => 36,
                "ne_tranh" => 36,
                "noi_phong" => 15,
                "bo_qua_noi_phong" => 45,
                "khi_huyet" => 447,
                "noi_luc" => 106,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 199225,
                "chan_khi_tong" => 7517230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 64,
                "chinh_xac" => 36,
                "ne_tranh" => 36,
                "noi_phong" => 15,
                "bo_qua_noi_phong" => 45,
                "khi_huyet" => 453,
                "noi_luc" => 108,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 202400,
                "chan_khi_tong" => 7716455,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 65,
                "chinh_xac" => 37,
                "ne_tranh" => 37,
                "noi_phong" => 15,
                "bo_qua_noi_phong" => 46,
                "khi_huyet" => 459,
                "noi_luc" => 109,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 205625,
                "chan_khi_tong" => 7918855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 66,
                "chinh_xac" => 37,
                "ne_tranh" => 37,
                "noi_phong" => 15,
                "bo_qua_noi_phong" => 46,
                "khi_huyet" => 465,
                "noi_luc" => 111,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 208900,
                "chan_khi_tong" => 8124480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 67,
                "chinh_xac" => 38,
                "ne_tranh" => 38,
                "noi_phong" => 16,
                "bo_qua_noi_phong" => 48,
                "khi_huyet" => 471,
                "noi_luc" => 112,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 212225,
                "chan_khi_tong" => 8333380,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 68,
                "chinh_xac" => 38,
                "ne_tranh" => 38,
                "noi_phong" => 16,
                "bo_qua_noi_phong" => 48,
                "khi_huyet" => 476,
                "noi_luc" => 113,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 215600,
                "chan_khi_tong" => 8545605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 69,
                "chinh_xac" => 39,
                "ne_tranh" => 39,
                "noi_phong" => 16,
                "bo_qua_noi_phong" => 49,
                "khi_huyet" => 482,
                "noi_luc" => 115,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 219025,
                "chan_khi_tong" => 8761205,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 70,
                "chinh_xac" => 39,
                "ne_tranh" => 39,
                "noi_phong" => 16,
                "bo_qua_noi_phong" => 49,
                "khi_huyet" => 488,
                "noi_luc" => 116,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 222500,
                "chan_khi_tong" => 8980230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 71,
                "chinh_xac" => 40,
                "ne_tranh" => 40,
                "noi_phong" => 17,
                "bo_qua_noi_phong" => 50,
                "khi_huyet" => 494,
                "noi_luc" => 118,
                "noi_luc_cooldown" => 2,
                "chan_khi_tien_cap" => 226025,
                "chan_khi_tong" => 9202730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 72,
                "chinh_xac" => 40,
                "ne_tranh" => 40,
                "noi_phong" => 17,
                "bo_qua_noi_phong" => 50,
                "khi_huyet" => 500,
                "noi_luc" => 119,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 229600,
                "chan_khi_tong" => 9428755,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 73,
                "chinh_xac" => 41,
                "ne_tranh" => 41,
                "noi_phong" => 17,
                "bo_qua_noi_phong" => 51,
                "khi_huyet" => 506,
                "noi_luc" => 121,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 233225,
                "chan_khi_tong" => 9658355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 74,
                "chinh_xac" => 41,
                "ne_tranh" => 41,
                "noi_phong" => 17,
                "bo_qua_noi_phong" => 51,
                "khi_huyet" => 512,
                "noi_luc" => 122,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 236900,
                "chan_khi_tong" => 9891580,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 75,
                "chinh_xac" => 42,
                "ne_tranh" => 42,
                "noi_phong" => 17,
                "bo_qua_noi_phong" => 52,
                "khi_huyet" => 518,
                "noi_luc" => 123,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 240625,
                "chan_khi_tong" => 10128480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 76,
                "chinh_xac" => 42,
                "ne_tranh" => 42,
                "noi_phong" => 17,
                "bo_qua_noi_phong" => 52,
                "khi_huyet" => 524,
                "noi_luc" => 125,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 244400,
                "chan_khi_tong" => 10369105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 77,
                "chinh_xac" => 43,
                "ne_tranh" => 43,
                "noi_phong" => 18,
                "bo_qua_noi_phong" => 54,
                "khi_huyet" => 530,
                "noi_luc" => 126,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 248225,
                "chan_khi_tong" => 10613505,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 78,
                "chinh_xac" => 43,
                "ne_tranh" => 43,
                "noi_phong" => 18,
                "bo_qua_noi_phong" => 54,
                "khi_huyet" => 536,
                "noi_luc" => 128,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 252100,
                "chan_khi_tong" => 10861730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 79,
                "chinh_xac" => 44,
                "ne_tranh" => 44,
                "noi_phong" => 18,
                "bo_qua_noi_phong" => 55,
                "khi_huyet" => 542,
                "noi_luc" => 129,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 256025,
                "chan_khi_tong" => 11113830,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 80,
                "chinh_xac" => 44,
                "ne_tranh" => 44,
                "noi_phong" => 18,
                "bo_qua_noi_phong" => 55,
                "khi_huyet" => 548,
                "noi_luc" => 130,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 260000,
                "chan_khi_tong" => 11369855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 81,
                "chinh_xac" => 45,
                "ne_tranh" => 45,
                "noi_phong" => 19,
                "bo_qua_noi_phong" => 56,
                "khi_huyet" => 554,
                "noi_luc" => 132,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 264025,
                "chan_khi_tong" => 11629855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 82,
                "chinh_xac" => 45,
                "ne_tranh" => 45,
                "noi_phong" => 19,
                "bo_qua_noi_phong" => 56,
                "khi_huyet" => 560,
                "noi_luc" => 133,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 268100,
                "chan_khi_tong" => 11893880,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 83,
                "chinh_xac" => 46,
                "ne_tranh" => 46,
                "noi_phong" => 19,
                "bo_qua_noi_phong" => 57,
                "khi_huyet" => 566,
                "noi_luc" => 135,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 272225,
                "chan_khi_tong" => 12161980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 84,
                "chinh_xac" => 46,
                "ne_tranh" => 46,
                "noi_phong" => 19,
                "bo_qua_noi_phong" => 57,
                "khi_huyet" => 571,
                "noi_luc" => 136,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 276400,
                "chan_khi_tong" => 12434205,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 85,
                "chinh_xac" => 47,
                "ne_tranh" => 47,
                "noi_phong" => 19,
                "bo_qua_noi_phong" => 58,
                "khi_huyet" => 577,
                "noi_luc" => 137,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 280625,
                "chan_khi_tong" => 12710605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 86,
                "chinh_xac" => 47,
                "ne_tranh" => 47,
                "noi_phong" => 19,
                "bo_qua_noi_phong" => 58,
                "khi_huyet" => 583,
                "noi_luc" => 139,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 284900,
                "chan_khi_tong" => 12991230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 87,
                "chinh_xac" => 48,
                "ne_tranh" => 48,
                "noi_phong" => 20,
                "bo_qua_noi_phong" => 60,
                "khi_huyet" => 589,
                "noi_luc" => 140,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 289225,
                "chan_khi_tong" => 13276130,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 88,
                "chinh_xac" => 48,
                "ne_tranh" => 48,
                "noi_phong" => 20,
                "bo_qua_noi_phong" => 60,
                "khi_huyet" => 595,
                "noi_luc" => 142,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 293600,
                "chan_khi_tong" => 13565355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 89,
                "chinh_xac" => 49,
                "ne_tranh" => 49,
                "noi_phong" => 20,
                "bo_qua_noi_phong" => 61,
                "khi_huyet" => 601,
                "noi_luc" => 143,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 298025,
                "chan_khi_tong" => 13858955,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 90,
                "chinh_xac" => 49,
                "ne_tranh" => 49,
                "noi_phong" => 20,
                "bo_qua_noi_phong" => 61,
                "khi_huyet" => 607,
                "noi_luc" => 145,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 302500,
                "chan_khi_tong" => 14156980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 91,
                "chinh_xac" => 50,
                "ne_tranh" => 50,
                "noi_phong" => 21,
                "bo_qua_noi_phong" => 62,
                "khi_huyet" => 613,
                "noi_luc" => 146,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 307025,
                "chan_khi_tong" => 14459480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 92,
                "chinh_xac" => 50,
                "ne_tranh" => 50,
                "noi_phong" => 21,
                "bo_qua_noi_phong" => 62,
                "khi_huyet" => 619,
                "noi_luc" => 147,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 311600,
                "chan_khi_tong" => 14766505,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 93,
                "chinh_xac" => 50,
                "ne_tranh" => 50,
                "noi_phong" => 21,
                "bo_qua_noi_phong" => 63,
                "khi_huyet" => 625,
                "noi_luc" => 149,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 316225,
                "chan_khi_tong" => 15078105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 94,
                "chinh_xac" => 50,
                "ne_tranh" => 50,
                "noi_phong" => 21,
                "bo_qua_noi_phong" => 63,
                "khi_huyet" => 631,
                "noi_luc" => 150,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 320900,
                "chan_khi_tong" => 15394330,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 95,
                "chinh_xac" => 51,
                "ne_tranh" => 51,
                "noi_phong" => 21,
                "bo_qua_noi_phong" => 64,
                "khi_huyet" => 637,
                "noi_luc" => 152,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 325625,
                "chan_khi_tong" => 15715230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 96,
                "chinh_xac" => 51,
                "ne_tranh" => 51,
                "noi_phong" => 21,
                "bo_qua_noi_phong" => 64,
                "khi_huyet" => 643,
                "noi_luc" => 153,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 330400,
                "chan_khi_tong" => 16040855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 97,
                "chinh_xac" => 52,
                "ne_tranh" => 52,
                "noi_phong" => 22,
                "bo_qua_noi_phong" => 66,
                "khi_huyet" => 649,
                "noi_luc" => 154,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 335225,
                "chan_khi_tong" => 16371255,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 98,
                "chinh_xac" => 52,
                "ne_tranh" => 52,
                "noi_phong" => 22,
                "bo_qua_noi_phong" => 66,
                "khi_huyet" => 655,
                "noi_luc" => 156,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 340100,
                "chan_khi_tong" => 16706480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 99,
                "chinh_xac" => 53,
                "ne_tranh" => 53,
                "noi_phong" => 22,
                "bo_qua_noi_phong" => 67,
                "khi_huyet" => 661,
                "noi_luc" => 157,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 345025,
                "chan_khi_tong" => 17046580,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 100,
                "chinh_xac" => 53,
                "ne_tranh" => 53,
                "noi_phong" => 22,
                "bo_qua_noi_phong" => 67,
                "khi_huyet" => 667,
                "noi_luc" => 159,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 350000,
                "chan_khi_tong" => 17391605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 101,
                "chinh_xac" => 54,
                "ne_tranh" => 54,
                "noi_phong" => 23,
                "bo_qua_noi_phong" => 68,
                "khi_huyet" => 672,
                "noi_luc" => 160,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 355025,
                "chan_khi_tong" => 17741605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 102,
                "chinh_xac" => 54,
                "ne_tranh" => 54,
                "noi_phong" => 23,
                "bo_qua_noi_phong" => 68,
                "khi_huyet" => 678,
                "noi_luc" => 162,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 360100,
                "chan_khi_tong" => 18096630,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 103,
                "chinh_xac" => 55,
                "ne_tranh" => 55,
                "noi_phong" => 23,
                "bo_qua_noi_phong" => 69,
                "khi_huyet" => 684,
                "noi_luc" => 163,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 365225,
                "chan_khi_tong" => 18456730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 104,
                "chinh_xac" => 55,
                "ne_tranh" => 55,
                "noi_phong" => 23,
                "bo_qua_noi_phong" => 69,
                "khi_huyet" => 690,
                "noi_luc" => 164,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 370400,
                "chan_khi_tong" => 18821955,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 105,
                "chinh_xac" => 56,
                "ne_tranh" => 56,
                "noi_phong" => 23,
                "bo_qua_noi_phong" => 70,
                "khi_huyet" => 696,
                "noi_luc" => 166,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 375625,
                "chan_khi_tong" => 19192355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 106,
                "chinh_xac" => 56,
                "ne_tranh" => 56,
                "noi_phong" => 23,
                "bo_qua_noi_phong" => 70,
                "khi_huyet" => 702,
                "noi_luc" => 167,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 380900,
                "chan_khi_tong" => 19567980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 107,
                "chinh_xac" => 57,
                "ne_tranh" => 57,
                "noi_phong" => 24,
                "bo_qua_noi_phong" => 72,
                "khi_huyet" => 708,
                "noi_luc" => 169,
                "noi_luc_cooldown" => 3,
                "chan_khi_tien_cap" => 386225,
                "chan_khi_tong" => 19948880,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 108,
                "chinh_xac" => 57,
                "ne_tranh" => 57,
                "noi_phong" => 24,
                "bo_qua_noi_phong" => 72,
                "khi_huyet" => 714,
                "noi_luc" => 170,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 391600,
                "chan_khi_tong" => 20335105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 109,
                "chinh_xac" => 58,
                "ne_tranh" => 58,
                "noi_phong" => 24,
                "bo_qua_noi_phong" => 73,
                "khi_huyet" => 720,
                "noi_luc" => 171,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 397025,
                "chan_khi_tong" => 20726705,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 110,
                "chinh_xac" => 58,
                "ne_tranh" => 58,
                "noi_phong" => 24,
                "bo_qua_noi_phong" => 73,
                "khi_huyet" => 726,
                "noi_luc" => 173,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 402500,
                "chan_khi_tong" => 21123730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 111,
                "chinh_xac" => 59,
                "ne_tranh" => 59,
                "noi_phong" => 25,
                "bo_qua_noi_phong" => 74,
                "khi_huyet" => 732,
                "noi_luc" => 174,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 408025,
                "chan_khi_tong" => 21526230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 112,
                "chinh_xac" => 59,
                "ne_tranh" => 59,
                "noi_phong" => 25,
                "bo_qua_noi_phong" => 74,
                "khi_huyet" => 738,
                "noi_luc" => 176,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 413600,
                "chan_khi_tong" => 21934255,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 113,
                "chinh_xac" => 60,
                "ne_tranh" => 60,
                "noi_phong" => 25,
                "bo_qua_noi_phong" => 75,
                "khi_huyet" => 744,
                "noi_luc" => 177,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 419225,
                "chan_khi_tong" => 22347855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 114,
                "chinh_xac" => 60,
                "ne_tranh" => 60,
                "noi_phong" => 25,
                "bo_qua_noi_phong" => 75,
                "khi_huyet" => 750,
                "noi_luc" => 178,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 424900,
                "chan_khi_tong" => 22767080,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 115,
                "chinh_xac" => 61,
                "ne_tranh" => 61,
                "noi_phong" => 25,
                "bo_qua_noi_phong" => 76,
                "khi_huyet" => 756,
                "noi_luc" => 180,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 430625,
                "chan_khi_tong" => 23191980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 116,
                "chinh_xac" => 61,
                "ne_tranh" => 61,
                "noi_phong" => 25,
                "bo_qua_noi_phong" => 76,
                "khi_huyet" => 762,
                "noi_luc" => 181,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 436400,
                "chan_khi_tong" => 23622605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 117,
                "chinh_xac" => 62,
                "ne_tranh" => 62,
                "noi_phong" => 26,
                "bo_qua_noi_phong" => 78,
                "khi_huyet" => 768,
                "noi_luc" => 183,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 442225,
                "chan_khi_tong" => 24059005,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 118,
                "chinh_xac" => 62,
                "ne_tranh" => 62,
                "noi_phong" => 26,
                "bo_qua_noi_phong" => 78,
                "khi_huyet" => 773,
                "noi_luc" => 184,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 448100,
                "chan_khi_tong" => 24501230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 119,
                "chinh_xac" => 63,
                "ne_tranh" => 63,
                "noi_phong" => 26,
                "bo_qua_noi_phong" => 79,
                "khi_huyet" => 779,
                "noi_luc" => 186,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 454025,
                "chan_khi_tong" => 24949330,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 120,
                "chinh_xac" => 63,
                "ne_tranh" => 63,
                "noi_phong" => 26,
                "bo_qua_noi_phong" => 79,
                "khi_huyet" => 785,
                "noi_luc" => 187,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 460000,
                "chan_khi_tong" => 25403355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 121,
                "chinh_xac" => 64,
                "ne_tranh" => 64,
                "noi_phong" => 27,
                "bo_qua_noi_phong" => 80,
                "khi_huyet" => 791,
                "noi_luc" => 188,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 466025,
                "chan_khi_tong" => 25863355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 122,
                "chinh_xac" => 64,
                "ne_tranh" => 64,
                "noi_phong" => 27,
                "bo_qua_noi_phong" => 80,
                "khi_huyet" => 797,
                "noi_luc" => 190,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 472100,
                "chan_khi_tong" => 26329380,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 123,
                "chinh_xac" => 65,
                "ne_tranh" => 65,
                "noi_phong" => 27,
                "bo_qua_noi_phong" => 81,
                "khi_huyet" => 803,
                "noi_luc" => 191,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 478225,
                "chan_khi_tong" => 26801480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 124,
                "chinh_xac" => 65,
                "ne_tranh" => 65,
                "noi_phong" => 27,
                "bo_qua_noi_phong" => 81,
                "khi_huyet" => 809,
                "noi_luc" => 193,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 484400,
                "chan_khi_tong" => 27279705,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 125,
                "chinh_xac" => 66,
                "ne_tranh" => 66,
                "noi_phong" => 27,
                "bo_qua_noi_phong" => 82,
                "khi_huyet" => 815,
                "noi_luc" => 194,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 490625,
                "chan_khi_tong" => 27764105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 126,
                "chinh_xac" => 66,
                "ne_tranh" => 66,
                "noi_phong" => 27,
                "bo_qua_noi_phong" => 82,
                "khi_huyet" => 821,
                "noi_luc" => 195,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 496900,
                "chan_khi_tong" => 28254730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 127,
                "chinh_xac" => 67,
                "ne_tranh" => 67,
                "noi_phong" => 28,
                "bo_qua_noi_phong" => 83,
                "khi_huyet" => 827,
                "noi_luc" => 197,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 503225,
                "chan_khi_tong" => 28751630,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 128,
                "chinh_xac" => 67,
                "ne_tranh" => 67,
                "noi_phong" => 28,
                "bo_qua_noi_phong" => 83,
                "khi_huyet" => 833,
                "noi_luc" => 198,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 509600,
                "chan_khi_tong" => 29254855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 129,
                "chinh_xac" => 68,
                "ne_tranh" => 68,
                "noi_phong" => 28,
                "bo_qua_noi_phong" => 85,
                "khi_huyet" => 839,
                "noi_luc" => 200,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 516025,
                "chan_khi_tong" => 29764455,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 130,
                "chinh_xac" => 68,
                "ne_tranh" => 68,
                "noi_phong" => 28,
                "bo_qua_noi_phong" => 85,
                "khi_huyet" => 845,
                "noi_luc" => 201,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 522500,
                "chan_khi_tong" => 30280480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 131,
                "chinh_xac" => 69,
                "ne_tranh" => 69,
                "noi_phong" => 29,
                "bo_qua_noi_phong" => 86,
                "khi_huyet" => 851,
                "noi_luc" => 203,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 529025,
                "chan_khi_tong" => 30802980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 132,
                "chinh_xac" => 69,
                "ne_tranh" => 69,
                "noi_phong" => 29,
                "bo_qua_noi_phong" => 86,
                "khi_huyet" => 857,
                "noi_luc" => 204,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 535600,
                "chan_khi_tong" => 31332005,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 133,
                "chinh_xac" => 70,
                "ne_tranh" => 70,
                "noi_phong" => 29,
                "bo_qua_noi_phong" => 87,
                "khi_huyet" => 863,
                "noi_luc" => 205,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 542225,
                "chan_khi_tong" => 31867605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 134,
                "chinh_xac" => 70,
                "ne_tranh" => 70,
                "noi_phong" => 29,
                "bo_qua_noi_phong" => 87,
                "khi_huyet" => 868,
                "noi_luc" => 207,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 548900,
                "chan_khi_tong" => 32409830,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 135,
                "chinh_xac" => 71,
                "ne_tranh" => 71,
                "noi_phong" => 29,
                "bo_qua_noi_phong" => 88,
                "khi_huyet" => 874,
                "noi_luc" => 208,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 555625,
                "chan_khi_tong" => 32958730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 136,
                "chinh_xac" => 71,
                "ne_tranh" => 71,
                "noi_phong" => 29,
                "bo_qua_noi_phong" => 88,
                "khi_huyet" => 880,
                "noi_luc" => 210,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 562400,
                "chan_khi_tong" => 33514355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 137,
                "chinh_xac" => 72,
                "ne_tranh" => 72,
                "noi_phong" => 30,
                "bo_qua_noi_phong" => 89,
                "khi_huyet" => 886,
                "noi_luc" => 211,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 569225,
                "chan_khi_tong" => 34076755,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 138,
                "chinh_xac" => 72,
                "ne_tranh" => 72,
                "noi_phong" => 30,
                "bo_qua_noi_phong" => 89,
                "khi_huyet" => 892,
                "noi_luc" => 212,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 576100,
                "chan_khi_tong" => 34645980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 139,
                "chinh_xac" => 73,
                "ne_tranh" => 73,
                "noi_phong" => 30,
                "bo_qua_noi_phong" => 91,
                "khi_huyet" => 898,
                "noi_luc" => 214,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 583025,
                "chan_khi_tong" => 35222080,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 140,
                "chinh_xac" => 73,
                "ne_tranh" => 73,
                "noi_phong" => 30,
                "bo_qua_noi_phong" => 91,
                "khi_huyet" => 904,
                "noi_luc" => 215,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 590000,
                "chan_khi_tong" => 35805105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 141,
                "chinh_xac" => 74,
                "ne_tranh" => 74,
                "noi_phong" => 31,
                "bo_qua_noi_phong" => 92,
                "khi_huyet" => 910,
                "noi_luc" => 217,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 597025,
                "chan_khi_tong" => 36395105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 142,
                "chinh_xac" => 74,
                "ne_tranh" => 74,
                "noi_phong" => 31,
                "bo_qua_noi_phong" => 92,
                "khi_huyet" => 916,
                "noi_luc" => 218,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 604100,
                "chan_khi_tong" => 36992130,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 143,
                "chinh_xac" => 74,
                "ne_tranh" => 74,
                "noi_phong" => 31,
                "bo_qua_noi_phong" => 93,
                "khi_huyet" => 922,
                "noi_luc" => 220,
                "noi_luc_cooldown" => 4,
                "chan_khi_tien_cap" => 611225,
                "chan_khi_tong" => 37596230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 144,
                "chinh_xac" => 74,
                "ne_tranh" => 74,
                "noi_phong" => 31,
                "bo_qua_noi_phong" => 93,
                "khi_huyet" => 928,
                "noi_luc" => 221,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 618400,
                "chan_khi_tong" => 38207455,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 145,
                "chinh_xac" => 75,
                "ne_tranh" => 75,
                "noi_phong" => 31,
                "bo_qua_noi_phong" => 94,
                "khi_huyet" => 934,
                "noi_luc" => 222,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 625625,
                "chan_khi_tong" => 38825855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 146,
                "chinh_xac" => 75,
                "ne_tranh" => 75,
                "noi_phong" => 31,
                "bo_qua_noi_phong" => 94,
                "khi_huyet" => 940,
                "noi_luc" => 224,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 632900,
                "chan_khi_tong" => 39451480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 147,
                "chinh_xac" => 76,
                "ne_tranh" => 76,
                "noi_phong" => 32,
                "bo_qua_noi_phong" => 95,
                "khi_huyet" => 946,
                "noi_luc" => 225,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 640225,
                "chan_khi_tong" => 40084380,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 148,
                "chinh_xac" => 76,
                "ne_tranh" => 76,
                "noi_phong" => 32,
                "bo_qua_noi_phong" => 95,
                "khi_huyet" => 952,
                "noi_luc" => 227,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 647600,
                "chan_khi_tong" => 40724605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 149,
                "chinh_xac" => 77,
                "ne_tranh" => 77,
                "noi_phong" => 32,
                "bo_qua_noi_phong" => 97,
                "khi_huyet" => 958,
                "noi_luc" => 228,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 655025,
                "chan_khi_tong" => 41372205,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 150,
                "chinh_xac" => 77,
                "ne_tranh" => 77,
                "noi_phong" => 32,
                "bo_qua_noi_phong" => 97,
                "khi_huyet" => 964,
                "noi_luc" => 229,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 662500,
                "chan_khi_tong" => 42027230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 151,
                "chinh_xac" => 78,
                "ne_tranh" => 78,
                "noi_phong" => 33,
                "bo_qua_noi_phong" => 98,
                "khi_huyet" => 969,
                "noi_luc" => 231,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 670025,
                "chan_khi_tong" => 42689730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 152,
                "chinh_xac" => 78,
                "ne_tranh" => 78,
                "noi_phong" => 33,
                "bo_qua_noi_phong" => 98,
                "khi_huyet" => 975,
                "noi_luc" => 232,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 677600,
                "chan_khi_tong" => 43359755,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 153,
                "chinh_xac" => 79,
                "ne_tranh" => 79,
                "noi_phong" => 33,
                "bo_qua_noi_phong" => 99,
                "khi_huyet" => 981,
                "noi_luc" => 234,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 685225,
                "chan_khi_tong" => 44037355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 154,
                "chinh_xac" => 79,
                "ne_tranh" => 79,
                "noi_phong" => 33,
                "bo_qua_noi_phong" => 99,
                "khi_huyet" => 987,
                "noi_luc" => 235,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 692900,
                "chan_khi_tong" => 44722580,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 155,
                "chinh_xac" => 80,
                "ne_tranh" => 80,
                "noi_phong" => 33,
                "bo_qua_noi_phong" => 100,
                "khi_huyet" => 993,
                "noi_luc" => 236,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 700625,
                "chan_khi_tong" => 45415480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 156,
                "chinh_xac" => 80,
                "ne_tranh" => 80,
                "noi_phong" => 33,
                "bo_qua_noi_phong" => 100,
                "khi_huyet" => 999,
                "noi_luc" => 238,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 708400,
                "chan_khi_tong" => 46116105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 157,
                "chinh_xac" => 81,
                "ne_tranh" => 81,
                "noi_phong" => 34,
                "bo_qua_noi_phong" => 101,
                "khi_huyet" => 1005,
                "noi_luc" => 239,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 716225,
                "chan_khi_tong" => 46824505,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 158,
                "chinh_xac" => 81,
                "ne_tranh" => 81,
                "noi_phong" => 34,
                "bo_qua_noi_phong" => 101,
                "khi_huyet" => 1011,
                "noi_luc" => 241,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 724100,
                "chan_khi_tong" => 47540730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 159,
                "chinh_xac" => 82,
                "ne_tranh" => 82,
                "noi_phong" => 34,
                "bo_qua_noi_phong" => 103,
                "khi_huyet" => 1017,
                "noi_luc" => 242,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 732025,
                "chan_khi_tong" => 48264830,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 160,
                "chinh_xac" => 82,
                "ne_tranh" => 82,
                "noi_phong" => 34,
                "bo_qua_noi_phong" => 103,
                "khi_huyet" => 1023,
                "noi_luc" => 244,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 740000,
                "chan_khi_tong" => 48996855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 161,
                "chinh_xac" => 83,
                "ne_tranh" => 83,
                "noi_phong" => 35,
                "bo_qua_noi_phong" => 104,
                "khi_huyet" => 1029,
                "noi_luc" => 245,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 748025,
                "chan_khi_tong" => 49736855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 162,
                "chinh_xac" => 83,
                "ne_tranh" => 83,
                "noi_phong" => 35,
                "bo_qua_noi_phong" => 104,
                "khi_huyet" => 1035,
                "noi_luc" => 246,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 756100,
                "chan_khi_tong" => 50484880,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 163,
                "chinh_xac" => 84,
                "ne_tranh" => 84,
                "noi_phong" => 35,
                "bo_qua_noi_phong" => 105,
                "khi_huyet" => 1041,
                "noi_luc" => 248,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 764225,
                "chan_khi_tong" => 51240980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 164,
                "chinh_xac" => 84,
                "ne_tranh" => 84,
                "noi_phong" => 35,
                "bo_qua_noi_phong" => 105,
                "khi_huyet" => 1047,
                "noi_luc" => 249,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 772400,
                "chan_khi_tong" => 52005205,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 165,
                "chinh_xac" => 85,
                "ne_tranh" => 85,
                "noi_phong" => 35,
                "bo_qua_noi_phong" => 106,
                "khi_huyet" => 1053,
                "noi_luc" => 251,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 780625,
                "chan_khi_tong" => 52777605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 166,
                "chinh_xac" => 85,
                "ne_tranh" => 85,
                "noi_phong" => 35,
                "bo_qua_noi_phong" => 106,
                "khi_huyet" => 1059,
                "noi_luc" => 252,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 788900,
                "chan_khi_tong" => 53558230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 167,
                "chinh_xac" => 86,
                "ne_tranh" => 86,
                "noi_phong" => 36,
                "bo_qua_noi_phong" => 107,
                "khi_huyet" => 1065,
                "noi_luc" => 253,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 797225,
                "chan_khi_tong" => 54347130,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 168,
                "chinh_xac" => 86,
                "ne_tranh" => 86,
                "noi_phong" => 36,
                "bo_qua_noi_phong" => 107,
                "khi_huyet" => 1070,
                "noi_luc" => 255,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 805600,
                "chan_khi_tong" => 55144355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 169,
                "chinh_xac" => 87,
                "ne_tranh" => 87,
                "noi_phong" => 36,
                "bo_qua_noi_phong" => 109,
                "khi_huyet" => 1076,
                "noi_luc" => 256,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 814025,
                "chan_khi_tong" => 55949955,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 170,
                "chinh_xac" => 87,
                "ne_tranh" => 87,
                "noi_phong" => 36,
                "bo_qua_noi_phong" => 109,
                "khi_huyet" => 1082,
                "noi_luc" => 258,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 822500,
                "chan_khi_tong" => 56763980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 171,
                "chinh_xac" => 88,
                "ne_tranh" => 88,
                "noi_phong" => 37,
                "bo_qua_noi_phong" => 110,
                "khi_huyet" => 1088,
                "noi_luc" => 259,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 831025,
                "chan_khi_tong" => 57586480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 172,
                "chinh_xac" => 88,
                "ne_tranh" => 88,
                "noi_phong" => 37,
                "bo_qua_noi_phong" => 110,
                "khi_huyet" => 1094,
                "noi_luc" => 261,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 839600,
                "chan_khi_tong" => 58417505,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 173,
                "chinh_xac" => 89,
                "ne_tranh" => 89,
                "noi_phong" => 37,
                "bo_qua_noi_phong" => 111,
                "khi_huyet" => 1100,
                "noi_luc" => 262,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 848225,
                "chan_khi_tong" => 59257105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 174,
                "chinh_xac" => 89,
                "ne_tranh" => 89,
                "noi_phong" => 37,
                "bo_qua_noi_phong" => 111,
                "khi_huyet" => 1106,
                "noi_luc" => 263,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 856900,
                "chan_khi_tong" => 60105330,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 175,
                "chinh_xac" => 90,
                "ne_tranh" => 90,
                "noi_phong" => 37,
                "bo_qua_noi_phong" => 112,
                "khi_huyet" => 1112,
                "noi_luc" => 265,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 865625,
                "chan_khi_tong" => 60962230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 176,
                "chinh_xac" => 90,
                "ne_tranh" => 90,
                "noi_phong" => 37,
                "bo_qua_noi_phong" => 112,
                "khi_huyet" => 1118,
                "noi_luc" => 266,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 874400,
                "chan_khi_tong" => 61827855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 177,
                "chinh_xac" => 91,
                "ne_tranh" => 91,
                "noi_phong" => 38,
                "bo_qua_noi_phong" => 113,
                "khi_huyet" => 1124,
                "noi_luc" => 268,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 883225,
                "chan_khi_tong" => 62702255,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 178,
                "chinh_xac" => 91,
                "ne_tranh" => 91,
                "noi_phong" => 38,
                "bo_qua_noi_phong" => 113,
                "khi_huyet" => 1130,
                "noi_luc" => 269,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 892100,
                "chan_khi_tong" => 63585480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 179,
                "chinh_xac" => 92,
                "ne_tranh" => 92,
                "noi_phong" => 38,
                "bo_qua_noi_phong" => 115,
                "khi_huyet" => 1136,
                "noi_luc" => 270,
                "noi_luc_cooldown" => 5,
                "chan_khi_tien_cap" => 901025,
                "chan_khi_tong" => 64477580,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 180,
                "chinh_xac" => 92,
                "ne_tranh" => 92,
                "noi_phong" => 38,
                "bo_qua_noi_phong" => 115,
                "khi_huyet" => 1142,
                "noi_luc" => 272,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 910000,
                "chan_khi_tong" => 65378605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 181,
                "chinh_xac" => 92,
                "ne_tranh" => 92,
                "noi_phong" => 39,
                "bo_qua_noi_phong" => 116,
                "khi_huyet" => 1148,
                "noi_luc" => 273,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 919025,
                "chan_khi_tong" => 66288605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 182,
                "chinh_xac" => 93,
                "ne_tranh" => 93,
                "noi_phong" => 39,
                "bo_qua_noi_phong" => 116,
                "khi_huyet" => 1154,
                "noi_luc" => 275,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 928100,
                "chan_khi_tong" => 67207630,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 183,
                "chinh_xac" => 93,
                "ne_tranh" => 93,
                "noi_phong" => 39,
                "bo_qua_noi_phong" => 117,
                "khi_huyet" => 1160,
                "noi_luc" => 276,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 937225,
                "chan_khi_tong" => 68135730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 184,
                "chinh_xac" => 94,
                "ne_tranh" => 94,
                "noi_phong" => 39,
                "bo_qua_noi_phong" => 117,
                "khi_huyet" => 1165,
                "noi_luc" => 277,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 946400,
                "chan_khi_tong" => 69072955,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 185,
                "chinh_xac" => 94,
                "ne_tranh" => 94,
                "noi_phong" => 39,
                "bo_qua_noi_phong" => 118,
                "khi_huyet" => 1171,
                "noi_luc" => 279,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 955625,
                "chan_khi_tong" => 70019355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 186,
                "chinh_xac" => 95,
                "ne_tranh" => 95,
                "noi_phong" => 40,
                "bo_qua_noi_phong" => 119,
                "khi_huyet" => 1177,
                "noi_luc" => 280,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 964900,
                "chan_khi_tong" => 70974980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 187,
                "chinh_xac" => 95,
                "ne_tranh" => 95,
                "noi_phong" => 40,
                "bo_qua_noi_phong" => 119,
                "khi_huyet" => 1183,
                "noi_luc" => 282,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 974225,
                "chan_khi_tong" => 71939880,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 188,
                "chinh_xac" => 96,
                "ne_tranh" => 96,
                "noi_phong" => 40,
                "bo_qua_noi_phong" => 120,
                "khi_huyet" => 1189,
                "noi_luc" => 283,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 983600,
                "chan_khi_tong" => 72914105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 189,
                "chinh_xac" => 96,
                "ne_tranh" => 96,
                "noi_phong" => 40,
                "bo_qua_noi_phong" => 120,
                "khi_huyet" => 1195,
                "noi_luc" => 285,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 993025,
                "chan_khi_tong" => 73897705,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 190,
                "chinh_xac" => 97,
                "ne_tranh" => 97,
                "noi_phong" => 40,
                "bo_qua_noi_phong" => 121,
                "khi_huyet" => 1201,
                "noi_luc" => 286,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1002500,
                "chan_khi_tong" => 74890730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 191,
                "chinh_xac" => 97,
                "ne_tranh" => 97,
                "noi_phong" => 41,
                "bo_qua_noi_phong" => 122,
                "khi_huyet" => 1207,
                "noi_luc" => 287,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1012025,
                "chan_khi_tong" => 75893230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 192,
                "chinh_xac" => 98,
                "ne_tranh" => 98,
                "noi_phong" => 41,
                "bo_qua_noi_phong" => 122,
                "khi_huyet" => 1213,
                "noi_luc" => 289,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1021600,
                "chan_khi_tong" => 76905255,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 193,
                "chinh_xac" => 98,
                "ne_tranh" => 98,
                "noi_phong" => 41,
                "bo_qua_noi_phong" => 123,
                "khi_huyet" => 1219,
                "noi_luc" => 290,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1031225,
                "chan_khi_tong" => 77926855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 194,
                "chinh_xac" => 99,
                "ne_tranh" => 99,
                "noi_phong" => 41,
                "bo_qua_noi_phong" => 123,
                "khi_huyet" => 1225,
                "noi_luc" => 292,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1040900,
                "chan_khi_tong" => 78958080,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 195,
                "chinh_xac" => 99,
                "ne_tranh" => 99,
                "noi_phong" => 41,
                "bo_qua_noi_phong" => 124,
                "khi_huyet" => 1231,
                "noi_luc" => 293,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1050625,
                "chan_khi_tong" => 79998980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 196,
                "chinh_xac" => 100,
                "ne_tranh" => 100,
                "noi_phong" => 42,
                "bo_qua_noi_phong" => 125,
                "khi_huyet" => 1237,
                "noi_luc" => 294,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1060400,
                "chan_khi_tong" => 81049605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 197,
                "chinh_xac" => 100,
                "ne_tranh" => 100,
                "noi_phong" => 42,
                "bo_qua_noi_phong" => 125,
                "khi_huyet" => 1243,
                "noi_luc" => 296,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1070225,
                "chan_khi_tong" => 82110005,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 198,
                "chinh_xac" => 101,
                "ne_tranh" => 101,
                "noi_phong" => 42,
                "bo_qua_noi_phong" => 126,
                "khi_huyet" => 1249,
                "noi_luc" => 297,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1080100,
                "chan_khi_tong" => 83180230,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 199,
                "chinh_xac" => 101,
                "ne_tranh" => 101,
                "noi_phong" => 42,
                "bo_qua_noi_phong" => 126,
                "khi_huyet" => 1255,
                "noi_luc" => 299,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1090025,
                "chan_khi_tong" => 84260330,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 200,
                "chinh_xac" => 102,
                "ne_tranh" => 102,
                "noi_phong" => 42,
                "bo_qua_noi_phong" => 127,
                "khi_huyet" => 1261,
                "noi_luc" => 300,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1100000,
                "chan_khi_tong" => 85350355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 201,
                "chinh_xac" => 102,
                "ne_tranh" => 102,
                "noi_phong" => 43,
                "bo_qua_noi_phong" => 128,
                "khi_huyet" => 1266,
                "noi_luc" => 302,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1110025,
                "chan_khi_tong" => 86450355,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 202,
                "chinh_xac" => 103,
                "ne_tranh" => 103,
                "noi_phong" => 43,
                "bo_qua_noi_phong" => 128,
                "khi_huyet" => 1272,
                "noi_luc" => 303,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1120100,
                "chan_khi_tong" => 87560380,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 203,
                "chinh_xac" => 103,
                "ne_tranh" => 103,
                "noi_phong" => 43,
                "bo_qua_noi_phong" => 129,
                "khi_huyet" => 1278,
                "noi_luc" => 304,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1130225,
                "chan_khi_tong" => 88680480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 204,
                "chinh_xac" => 103,
                "ne_tranh" => 103,
                "noi_phong" => 43,
                "bo_qua_noi_phong" => 129,
                "khi_huyet" => 1284,
                "noi_luc" => 306,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1140400,
                "chan_khi_tong" => 89810705,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 205,
                "chinh_xac" => 104,
                "ne_tranh" => 104,
                "noi_phong" => 43,
                "bo_qua_noi_phong" => 130,
                "khi_huyet" => 1290,
                "noi_luc" => 307,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1150625,
                "chan_khi_tong" => 90951105,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 206,
                "chinh_xac" => 104,
                "ne_tranh" => 104,
                "noi_phong" => 44,
                "bo_qua_noi_phong" => 131,
                "khi_huyet" => 1296,
                "noi_luc" => 309,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1160900,
                "chan_khi_tong" => 92101730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 207,
                "chinh_xac" => 105,
                "ne_tranh" => 105,
                "noi_phong" => 44,
                "bo_qua_noi_phong" => 131,
                "khi_huyet" => 1302,
                "noi_luc" => 310,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1171225,
                "chan_khi_tong" => 93262630,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 208,
                "chinh_xac" => 105,
                "ne_tranh" => 105,
                "noi_phong" => 44,
                "bo_qua_noi_phong" => 132,
                "khi_huyet" => 1308,
                "noi_luc" => 311,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1181600,
                "chan_khi_tong" => 94433855,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 209,
                "chinh_xac" => 106,
                "ne_tranh" => 106,
                "noi_phong" => 44,
                "bo_qua_noi_phong" => 132,
                "khi_huyet" => 1314,
                "noi_luc" => 313,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1192025,
                "chan_khi_tong" => 95615455,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 210,
                "chinh_xac" => 106,
                "ne_tranh" => 106,
                "noi_phong" => 44,
                "bo_qua_noi_phong" => 133,
                "khi_huyet" => 1320,
                "noi_luc" => 314,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1202500,
                "chan_khi_tong" => 96807480,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 211,
                "chinh_xac" => 107,
                "ne_tranh" => 107,
                "noi_phong" => 45,
                "bo_qua_noi_phong" => 134,
                "khi_huyet" => 1326,
                "noi_luc" => 316,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1213025,
                "chan_khi_tong" => 98009980,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 212,
                "chinh_xac" => 107,
                "ne_tranh" => 107,
                "noi_phong" => 45,
                "bo_qua_noi_phong" => 134,
                "khi_huyet" => 1332,
                "noi_luc" => 317,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1223600,
                "chan_khi_tong" => 99223005,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 213,
                "chinh_xac" => 108,
                "ne_tranh" => 108,
                "noi_phong" => 45,
                "bo_qua_noi_phong" => 135,
                "khi_huyet" => 1338,
                "noi_luc" => 319,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1234225,
                "chan_khi_tong" => 100446605,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 214,
                "chinh_xac" => 108,
                "ne_tranh" => 108,
                "noi_phong" => 45,
                "bo_qua_noi_phong" => 135,
                "khi_huyet" => 1344,
                "noi_luc" => 320,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1244900,
                "chan_khi_tong" => 101680830,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 215,
                "chinh_xac" => 109,
                "ne_tranh" => 109,
                "noi_phong" => 45,
                "bo_qua_noi_phong" => 136,
                "khi_huyet" => 1350,
                "noi_luc" => 321,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1255625,
                "chan_khi_tong" => 102925730,
            ],
            [
                "kinh_mach_id" => 1,
                "level" => 216,
                "chinh_xac" => 109,
                "ne_tranh" => 109,
                "noi_phong" => 46,
                "bo_qua_noi_phong" => 137,
                "khi_huyet" => 1356,
                "noi_luc" => 200,
                "noi_luc_cooldown" => 7,
                "chan_khi_tien_cap" => 1266400,
                "chan_khi_tong" => 104181355,
            ],
        ];
        $table = $this->table("kinh_mach_detail");
        $table->truncate();

        foreach ($data as $d) {
            $d["created_at"] = date("Y-m-d H:i:s");
            $d["updated_at"] = date("Y-m-d H:i:s");
            $table->insert($d)
                ->save();
        }
    }
}
